### ISSUE TITLE
Failing to display Ad in React environments, also crashing the websites

### ISSUE THREAD

**Issue by karthikdivi** [readthedocs/ethical-ad-client#59]
Observing this issue from a week. I am able to reproduce the issue in the following code sandbox environment. 

https://codesandbox.io/s/hopeful-leaf-b8s5i?file=/src/Ad.js:386-859

To reproduce please comment and uncomment the `React.useEffect` snippet i.e from line # 17 to # 34

```
Possible Unhandled Promise Rejection: 
TypeError: Failed to construct 'URL': Please use the 'new' operator.
    at new s (https://media.ethicalads.io/media/client/ethicalads.min.js:1:17327)

    at https://media.ethicalads.io/media/client/ethicalads.min.js:1:18403

    at new s (https://media.ethicalads.io/media/client/ethicalads.min.js:1:18464)

    at e.value (https://media.ethicalads.io/media/client/ethicalads.min.js:1:11362)

    at e.value (https://media.ethicalads.io/media/client/ethicalads.min.js:1:10473)

    at https://media.ethicalads.io/media/client/ethicalads.min.js:1:13495

    at Array.map (<anonymous>)

    at _ (https://media.ethicalads.io/media/client/ethicalads.min.js:1:13248)

    at https://media.ethicalads.io/media/client/ethicalads.min.js:1:14271

    at https://media.ethicalads.io/media/client/ethicalads.min.js:1:1476

    at https://codesandbox.io/static/js/vendors~react-devtools-backend.d7ac7a663.chunk.js:1:62677

    at c (https://codesandbox.io/static/js/vendors~react-devtools-backend.d7ac7a663.chunk.js:1:62792)

    at n (https://codesandbox.io/static/js/vendors~react-devtools-backend.d7ac7a663.chunk.js:1:61737)
```

<img width="1417" alt="Screenshot 2021-04-30 at 12 24 38 PM" src="https://user-images.githubusercontent.com/3498914/116659312-0ac53780-a9af-11eb-92f0-dce4e916da5f.png">

**Comment by davidfischer** [comment]
@karthikdivi Thanks for the report. I've seen a few issues like this but it's very puzzling to me. I loaded up your snippet and it works fine for me. I'm not very familiar with React so I'm not sure what would cause this. We do [polyfill the URL](https://github.com/readthedocs/ethical-ad-client/blob/main/polyfills.js) object in order to support IE11 and it might be related to that. I also wonder if this is confusing things that should happen once with things that should happen periodically, somehow.


![Screenshot from 2021-05-03 11-56-52](https://user-images.githubusercontent.com/185043/116919835-bc11da80-ac06-11eb-832e-d0da2477ed2a.png)

**Comment by davidfischer** [comment]
I think I see what's happening. I am able to reproduce this error when I load the script twice.

**Comment by karthikdivi** [comment]
@davidfischer Yes it's not consistent. What my learning is it does not happen on first render but happens when react do a client side reload. To mimic that behaviour we need to toggle the code you have hi-lighted above. 
This started happening from a week, do you think any recent changes has chances of introducing this?

**Comment by davidfischer** [comment]
We added the polyfill about two weeks ago to support some old browsers.

**Comment by davidfischer** [comment]
This should now be fixed.

**Comment by oliviertassinari** [comment]
to be reopend. it's not fixed: https://github.com/mui-org/material-ui/issues/27153.

**Comment by karthikdivi** [comment]
Yes @oliviertassinari  It's not fixed yet. 
The replication steps I have provided above are still valid and we can re-produce it. 

@davidfischer can you please re-open this and check the issue?
